# CountDataSet function from PoiClaClu package or DESeq package.
# This function assumes DE rate to be constant at 30%. We modify the function to control DE parameter.
generateCountData <- function (n = 10, p = 20, K = 2, param = 1, sdsignal = 1, DE = 0.3, 
                               allZero.rm = TRUE, tag.samples = FALSE, 
                               improper = FALSE, improper.ratio = c(0.5, 0.15)) {
  # Args:
  #   n: number of samples
  #   p: number of features
  #   K: number of classes
  #   sdsignal: The extent to which the classes are different. If this equals zero then there 
  #             are no class differences and if this is large then the classes are very different.
  #             This parameter is used to siulate dkj parameters.
  #   DE: probability of a gene being differentially expressed between classes.
  #   allZero.rm: a logical. If TRUE, features with only zero counts will be removed. Otherwise, it will be kept
  #               in the model as a presence of excess zeros. Might be suitable for zero-inflated scenarios.
  #   param: dispersion parameter. Overdispersion parameter is equal to 1/param.
  
  if (n < 4 * K){
    stop("We require n to be at least 4*K.")
  }
  
  if (DE < 0 || DE > 1){
    stop("DE should be a value within [0, 1].")
  }
  
  q0 <- rexp(p, rate = 1/25)   # Gene total, g.j
  isDE <- runif(p) <= DE
  
  # Defining if a feature is improper in count distribution or not.
  # Half of the DE features and 15% of non-DE features are set to be improper in counts.
  if (improper){
    isImproper <- sapply(isDE, function(x){
      ifelse(x, runif(1) < 0.5, runif(1) < .15)
    })  
  } else {
    isImproper <- rep(FALSE, p)
  }
  
  classk <- matrix(NA, nrow = K, ncol = p)
  
  for (k in 1:K) {
    # dkj parameters
    lfc <- rnorm(p, sd = sdsignal)   
    
    ## Hangi genlerin DE olduğu bilgisi. Bunları da generate edilen veri ile döndürebiliriz.
    classk[k, ] <- ifelse(isDE, q0 * exp(lfc), q0)   
  }
  
  truesf <- runif(n) * 2 + 0.2
  truesfte <- runif(n) * 2 + 0.2
  conds <- sample(c(rep(1:K, 4), sample(1:K, n - 4 * K, replace = TRUE)))
  condste <- sample(c(rep(1:K, 4), sample(1:K, n - 4 * K, replace = TRUE)))
  x <- xte <- matrix(NA, nrow = n, ncol = p)
  
  # IMPROPER YAPIDA VERİ ÜRETME KISMI BURADA DÜZENLENECEK.
  for (i in 1:n) {
    for (k in 1:K) {
      if (conds[i] == k) 
        x[i, ] <- rnbinom(p, mu = truesf[i] * classk[k, ], size = param)
      if (condste[i] == k) 
        xte[i, ] <- rnbinom(p, mu = truesfte[i] * classk[k, ], size = param)
    }
  }
  
  if (allZero.rm){
    rm <- apply(x, 2, sum) == 0   # Removes all zero columns.  
  } else {
    rm <- logical(ncol(x))
  }
  
  # x <- as.data.frame(x)
  # xte <- as.data.frame(xte)
  colnames(x) <- colnames(xte) <- paste("G", 1:p, sep = "")
  
  if (tag.samples){
    rownames(x) <- rownames(xte) <- paste("S", 1:n, sep = "")
  }
  
  return(structure(list(x = t(x[, !rm]), xte = t(xte[, !rm]), y = conds, yte = condste, 
                        truesf = truesf, truesfte = truesfte, DE.Genes = isDE), class = "count.data"))
}


# object: a list returned from "generateCountData" function.
createDDSobject <- function(.counts, .y, ...){
  if (!is.factor(.y) & is.numeric(.y)){
    classes <- paste0("C", .y)
  }
  .y <- as.factor(.y)
  
  nClasses <- length(unique(.y))
  
  coldata <- data.frame(
    condition = .y
  )
  rownames(coldata) <- colnames(.counts)
  
  dds <- DESeqDataSetFromMatrix(countData = .counts,
                                colData = coldata,
                                design = ~ condition,
                                ...)
  return(dds)
}


# object: an object returned from "createDDSobject" function.
filterLowQualityGenes <- function(object, filterLowCounts = TRUE, filterNearZeroVariance = TRUE, 
                                  lc.threshold = 10, smallestGroupSize = 3, ...){
  
  if (!inherits(object, "DESeqDataSet")){
    stop("'object' must be of 'DESeqDataSet' class generated by the function 'DESeqDataSetFromMatrix'.")
  }
  
  # Keep features having mapped read counts above "lc.threshold" from at least "smallestGroupSize" samples.
  # Here we perform pre-filtering to keep only rows that have a count of at least 10 for a minimal 
  # number of samples. The count of 10 is a reasonable choice for bulk RNA-seq. A recommendation 
  # for the minimal number of samples is to specify the smallest group size, e.g. here there 
  # are 3 treated samples.
  if (filterLowCounts){
    keep <- rowSums(counts(object) >= lc.threshold) >= smallestGroupSize
    object <- object[keep, ]
  }
  
  # Near-zero variance filtering
  if (filterNearZeroVariance){
    nzVar <- caret::nearZeroVar(t(counts(object)), ...)
    if (length(nzVar) > 0){
      dds <- dds[-nzVar, ]  
    }
  }
  
  return(object)
}


# object: an object returned from "createDDSobject" function or filtered object returned by
# "filterCounts" function.
applyDESeq <- function(object, normalize = TRUE, transform = TRUE, 
                       transformationMethod = c("vst", "rlog", "logCPM"), nonzero = FALSE, ...){
  
  if (!inherits(object, "DESeqDataSet")){
    stop("'object' must be of 'DESeqDataSet' class generated by the function 'DESeqDataSetFromMatrix'.")
  }
  
  if (nonzero){
    counts(object) <- counts(object) + 1L  
  }
  
  object.init <- object
  transformationMethod <- match.arg(transformationMethod)
  
  normalizedCounts <- transformedCounts <- NULL
  
  object_DESeq <- try({
    DESeq(object, ...)
  })
  
  if (normalize){
    normalizedCounts <- counts(object_DESeq, normalize = TRUE)
  }
  
  if (transform){
    if (transformationMethod == "vst"){
      success <- try({
        object_DESeqTransform <- varianceStabilizingTransformation(object_DESeq)
      })
      
      if (!inherits(success, "try-error")){
        transformedCounts <- assay(object_DESeqTransform)  
      } else {
        transformedCounts <- NULL
      }
    }
  }
  
  return(list(
    DESeqObject = object_DESeq, 
    normalizedCounts = normalizedCounts,
    transformedCounts = vstCounts
  ))
}

selectDEfeatures <- function(object, nFeatures = 5, ...){
  
  if (!inherits(object, "DESeqDataSet")){
    stop("'object' must be of 'DESeqDataSet' class generated by the function 'DESeq'.")
  }
 
  # object <- DESeq(object)
  res <- results(object, ...)
  res <- res[order(abs(res$stat), decreasing = TRUE), ]
  
  selectedFeatures <- rownames(res)[1:nFeatures]
  
  return(list(
    DESeqObject = object,
    DESeqResults = res,
    selectedFeatures = selectedFeatures
  ))
}



sampleData <- read.table("data/CervicalCO.txt", row.names = 1)
cls <- as.factor(rep(c("N", "T"), each = 29))
object <- list(x = sampleData, y = cls)

dds <- createDDSobject(.counts = object$x, .y = object$y)
dds_filtered <- filterLowQualityGenes(dds)
